using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;


/*
            ..:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::..          
           .:╔════════════════════════════════════════════════════════════════╗:.       
           :╔╩╗                                                              ╔╩╗:       
           :║▒║     ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓ ▓▓      ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓     ▓▓▓    ║▒║:      
          :║▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓   ▓▓ ▓▓    ║▒▒║:    
         :║▒▒▒║     ▓▓▓▓▓   ▓▓▓▓▓▓▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓  ▓▓  ▓▓    ║▒▒▒║:    
        :║▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓ ▓▓   ▓▓    ║▒▒▒▒║:   
       :║▒▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓▓▓    ▓▓    ║▒▒▒▒▒║:  
       :║▒▒▒▒▒║                                                              ║▒▒▒▒▒║:  
        :║▒▒▒▒║                       • FRoundButton •                       ║▒▒▒▒║:  
         :║▒▒▒║                     -------------------                      ║▒▒▒║:    
          :║▒▒║                   Round Windows Form Button                  ║▒▒║:     
           :║▒║               © Generated BY FALAH FATHEL • 2026             ║▒║:      
           :╚╦╝               |Github|www.github.com/FALCONZeroX             ╚╦╝:     
            :╚════════════════════════════════════════════════════════════════╝:'      
            '':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::''  
*/

namespace RoundButton
{
    public class FRoundButton : Button
    {
        //Fields
        private int borderSize = 0;
        private int borderRadius = 50;
        private Color borderColor = Color.BlueViolet;

        //Properties
        public int BorderSize
        {
            get => borderSize;
            set { borderSize = value; Invalidate(); }
        }
        public int BorderRadius
        {
            get => borderRadius;
            set { borderRadius = (value <= Height) ? value : Height; Invalidate(); }
        }
        public Color BackgroundColor
        {
            get => BackColor;
            set { BackColor = value; }
        }
        public Color TextColor
        {
            get => ForeColor;
            set { ForeColor = value; }
        }

        //Constructor
        public FRoundButton()
        {
            Size = new Size(200, 100);
            FlatAppearance.BorderSize = 0;
            FlatStyle = FlatStyle.Flat;
            BackColor = Color.BlueViolet;
            ForeColor = Color.White;
            Resize += new EventHandler(Button_Resize);

        }

        private void Button_Resize(object sender, EventArgs e)
        {
            if (BorderRadius > Height) borderRadius = Height;
        }

        //Methods
        private GraphicsPath GetFigurePath(RectangleF rectangle, float Radius)
        {
            GraphicsPath graphicpath = new GraphicsPath();
            graphicpath.StartFigure();
            graphicpath.AddArc(rectangle.X, rectangle.Y, Radius,Radius, 180, 90);
            graphicpath.AddArc(rectangle.Width - Radius, rectangle.Y, Radius, Radius, 270, 90);
            graphicpath.AddArc(rectangle.Width - Radius, rectangle.Height - Radius, Radius, Radius, 0, 90);
            graphicpath.AddArc(rectangle.X, rectangle.Height - Radius, Radius, Radius, 90, 90);
            graphicpath.CloseFigure();

            return graphicpath;
        }

        protected override void OnPaint(PaintEventArgs pevent)
        {
            base.OnPaint(pevent);
            pevent.Graphics.SmoothingMode = SmoothingMode.AntiAlias;

            RectangleF rectangleSurface = new RectangleF(0, 0, Width, Height);
            RectangleF rectangleBorder = new RectangleF(1, 1, Width - 0.5F, Height - 1);

            if (borderRadius > 1)
            {
                using (GraphicsPath graphicsPathSurface = GetFigurePath(rectangleSurface, borderRadius))
                using (GraphicsPath graphicsPathBorder = GetFigurePath(rectangleBorder, borderRadius - 1F))
                using (Pen penSurface = new Pen(this.Parent != null ? this.Parent.BackColor : Color.White, 2))
                using (Pen penBorder = new Pen(borderColor, borderSize))
                {
                    penBorder.Alignment = PenAlignment.Inset;
                    Region = new Region(graphicsPathSurface);

                    pevent.Graphics.DrawPath(penSurface, graphicsPathSurface);

                    if (borderSize >= 1)
                    {
                        pevent.Graphics.DrawPath(penBorder, graphicsPathBorder);
                    }
                }
            }
            else
            {
                Region = new Region(rectangleSurface);
                if (borderSize >= 1)
                {
                    using (Pen penBorder = new Pen(borderColor, borderSize))
                    {
                        penBorder.Alignment = PenAlignment.Inset;
                        pevent.Graphics.DrawRectangle(penBorder, 0, 0, Width - 1, Height - 1);
                    }
                }
            }
        }
        protected override void OnHandleCreated(EventArgs e)
        {
            base.OnHandleCreated(e);

            if (System.ComponentModel.LicenseManager.UsageMode == System.ComponentModel.LicenseUsageMode.Designtime) 
                return;
            Parent.BackColorChanged += new EventHandler(Container_BackColorChange);
        }
        private void Container_BackColorChange(object sender, EventArgs e)
        {
            if (DesignMode) Invalidate();
    
        }
    }
}
