using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;

/*
            ..:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::..          
           .:╔════════════════════════════════════════════════════════════════╗:.       
           :╔╩╗                                                              ╔╩╗:       
           :║▒║     ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓ ▓▓      ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓     ▓▓▓    ║▒║:      
          :║▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓   ▓▓ ▓▓    ║▒▒║:    
         :║▒▒▒║     ▓▓▓▓▓   ▓▓▓▓▓▓▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓  ▓▓  ▓▓    ║▒▒▒║:    
        :║▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓ ▓▓   ▓▓    ║▒▒▒▒║:   
       :║▒▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓▓▓    ▓▓    ║▒▒▒▒▒║:  
       :║▒▒▒▒▒║                                                              ║▒▒▒▒▒║:  
        :║▒▒▒▒║                        • FRoundPanel •                       ║▒▒▒▒║:  
         :║▒▒▒║                     -------------------                      ║▒▒▒║:    
          :║▒▒║                    Round Windows Form Panel                  ║▒▒║:     
           :║▒║               © Generated BY FALAH FATHEL • 2026             ║▒║:      
           :╚╦╝               |Github|www.github.com/FALCONZeroX             ╚╦╝:     
            :╚════════════════════════════════════════════════════════════════╝:'      
            '':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::''  
*/

namespace RoundPanel
{
    public class FRoundPanel : Panel
    {
        public FRoundPanel()
        {
            this.DoubleBuffered = true;
            this.Size = new Size(60, 30); // Perfect Size
            this.BackColor = Color.FromArgb(27, 32, 48); // Panel Default Back Color
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            Graphics g = e.Graphics;

            // 1. Clean Background with Father Container
            if (this.Parent != null)
            {
                g.Clear(this.Parent.BackColor);
            }

            // 2. Enable Anti-Alising
            g.SmoothingMode = SmoothingMode.AntiAlias;
            g.CompositingQuality = CompositingQuality.HighQuality;

            // 3. Math Calc for Round Panel
            int diameter = this.Height - 1;
            Rectangle rectLeft = new Rectangle(0, 0, diameter, diameter);
            Rectangle rectRight = new Rectangle(this.Width - diameter - 1, 0, diameter, diameter);

            using (GraphicsPath paintPath = new GraphicsPath())
            {
                paintPath.AddArc(rectLeft, 90, 180);
                paintPath.AddArc(rectRight, 270, 180);
                paintPath.CloseFigure();

                // 4. Fill With Color
                using (SolidBrush brush = new SolidBrush(this.BackColor))
                {
                    g.FillPath(brush, paintPath);
                }
            }
        }

        protected override void OnResize(EventArgs eventargs)
        {
            base.OnResize(eventargs);
            this.Invalidate(); 
        }
    }
}